name: 'linear-app-create-issue'
description: 'GitHub Action to create an Issue for Linear.app.'

branding:
  icon: check-square
  color: purple
author: 'Futa Hirakoba <korosuke613613@gmail.com>'

inputs:
  issueFilePath: # change this
    required: true
    description: 'File path of Issue markdown.'
  apiKey: # change this
    required: true
    description: 'api key of Linear.app.'
  teamId: # change this
    required: true
    description: 'team id of Linear.app.'
  stateId: # change this
    required: true
    description: 'state id of Linear.app.'
  isDryrun: # change this
    required: false
    description: 'enable dryrun'

runs:
  using: 'node12'
  main: 'dist/index.js'
